-- ================================================================
-- SKPO V2 — STRUKTUR PANGKALAN DATA SUPABASE
-- Jalankan sekali dalam Supabase SQL Editor.
-- ================================================================

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  no_badan text unique not null,
  pangkat text,
  nama text not null,
  peranan text not null default 'PETUGAS'
    check (peranan in ('PETUGAS','PENYELIA','URUSETIA','PENTADBIR','TSM')),
  telefon text,
  bahagian text,
  daerah text,
  aktif boolean not null default true,
  device_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.penugasan (
  id uuid primary key default gen_random_uuid(),
  tarikh date not null,
  petugas_id uuid not null references public.profiles(id) on delete cascade,
  call_sign text,
  jenis_tugas text not null,
  tempat_tugas text not null,
  penyelia boolean not null default false,
  pemegang_set boolean not null default false,
  latitude numeric(10,7),
  longitude numeric(10,7),
  radius_meter integer not null default 30 check (radius_meter > 0),
  status text not null default 'AKTIF' check (status in ('AKTIF','DIGANTI')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tarikh, petugas_id)
);

create table if not exists public.checkin (
  id uuid primary key default gen_random_uuid(),
  penugasan_id uuid not null references public.penugasan(id) on delete cascade,
  petugas_id uuid not null references public.profiles(id) on delete cascade,
  tarikh date not null,
  masa_checkin timestamptz not null default now(),
  latitude numeric(10,7) not null,
  longitude numeric(10,7) not null,
  ketepatan_gps numeric,
  jarak_meter numeric,
  device_id text,
  status text not null default 'MENUNGGU'
    check (status in ('MENUNGGU','HADIR','DITOLAK')),
  disahkan_oleh uuid references auth.users(id),
  masa_pengesahan timestamptz,
  sebab_ditolak text,
  created_at timestamptz not null default now(),
  unique (petugas_id, tarikh)
);

create table if not exists public.checkout (
  id uuid primary key default gen_random_uuid(),
  checkin_id uuid not null references public.checkin(id) on delete cascade,
  penugasan_id uuid not null references public.penugasan(id) on delete cascade,
  petugas_id uuid not null references public.profiles(id) on delete cascade,
  tarikh date not null,
  masa_checkout timestamptz not null default now(),
  latitude numeric(10,7) not null,
  longitude numeric(10,7) not null,
  ketepatan_gps numeric,
  jarak_meter numeric,
  tempoh_minit integer,
  status text not null default 'SELESAI TUGAS',
  created_at timestamptz not null default now(),
  unique (petugas_id, tarikh)
);

create table if not exists public.pelaporan (
  id uuid primary key default gen_random_uuid(),
  penugasan_id uuid not null references public.penugasan(id) on delete cascade,
  petugas_id uuid not null references public.profiles(id) on delete cascade,
  tarikh_masa timestamptz not null default now(),
  jumlah_pengunjung integer not null check (jumlah_pengunjung >= 0),
  jumlah_kenderaan integer not null check (jumlah_kenderaan >= 0),
  vvip_vip text not null,
  perkara_menarik text not null,
  status_bacaan text not null default 'BELUM DIBACA',
  dibaca_oleh uuid references auth.users(id),
  masa_dibaca timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.walkie_talkie (
  id uuid primary key default gen_random_uuid(),
  penugasan_id uuid not null references public.penugasan(id) on delete cascade,
  petugas_id uuid not null references public.profiles(id) on delete cascade,
  no_siri_set text,
  no_siri_bateri text,
  no_siri_charger text,
  aksesori text[] not null default '{}',
  catatan_petugas text,
  status text not null default 'MENUNGGU'
    check (status in ('MENUNGGU','DILEPASKAN','DITOLAK','MENUNGGU_PEMULANGAN','DIPULANGKAN')),
  masa_permohonan timestamptz not null default now(),
  masa_pelepasan timestamptz,
  disahkan_oleh uuid references auth.users(id),
  sebab_ditolak text,
  masa_permohonan_pemulangan timestamptz,
  masa_pemulangan timestamptz,
  diterima_oleh uuid references auth.users(id),
  keadaan_set text,
  kerosakan text,
  catatan_tsm text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (penugasan_id, petugas_id)
);

create table if not exists public.log_aktiviti (
  id bigint generated by default as identity primary key,
  pelaku_id uuid references auth.users(id),
  tindakan text not null,
  sasaran_id text,
  butiran jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_penugasan_tarikh on public.penugasan(tarikh);
create index if not exists idx_checkin_tarikh on public.checkin(tarikh);
create index if not exists idx_checkout_tarikh on public.checkout(tarikh);
create index if not exists idx_walkie_status on public.walkie_talkie(status);
create index if not exists idx_pelaporan_petugas on public.pelaporan(petugas_id, tarikh_masa);
